# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: dotnet build --configuration Debug
  displayName: 'Build Debug'

- script: dotnet build --configuration Release
  displayName: 'Build Release'

- script: dotnet test --logger trx --framework netcoreapp2.2
- task: PublishTestResults@2
  displayName: 'Test NetCore'
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet test --logger trx --framework net45
- task: PublishTestResults@2
  displayName: 'Test NetFramework'
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'